/*
* generated by Xtext
*/
package com.btc.arch.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ArchitectureDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
