/*
* generated by Xtext
*/
package com.btc.arch.ui.contentassist;

import com.btc.arch.ui.contentassist.AbstractArchitectureDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ArchitectureDslProposalProvider extends AbstractArchitectureDslProposalProvider {

}
